name: ldaca-binder
channels:
  - conda-forge
dependencies:
  - python=3.10
  - nodejs=20
  - pip
  - pip:
      - fastapi==0.110.0
      - uvicorn[standard]==0.23.2
      - jupyter-server-proxy==4.1.2
      - sqlalchemy[asyncio]
      - aiosqlite
      - httpx
      - python-multipart
      - pydantic-settings
