name: repo2docker-dockerhub
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-push:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Optionally convert README to index.ipynb
      run: |
        python -m pip install -U pip jupytext jupyterlab
        if [ -f README.md ]; then
          sed '/^<\!-- START RUN INFO/,/^<\!-- END RUN INFO/d;' README.md > index.md || cp README.md index.md
          jupytext -k python3 --to ipynb index.md || true
        fi

    - name: Build and push with repo2docker (Docker Hub)
      id: r2d
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        DOCKER_REGISTRY: docker.io
        IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
        # Do not set BINDER_CACHE (Quay-specific)

    - name: Compute short SHA and image ref
      run: |
        SHORT_SHA="${GITHUB_SHA::12}"
        echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
        echo "IMAGE_REF=${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:$SHORT_SHA" >> $GITHUB_ENV

    - name: Update binder/Dockerfile to new image tag
      run: |
        {
          echo "# Github Action Built Image"
          echo "FROM $IMAGE_REF"
          echo
          echo "# Auto-run start script to launch backend/frontend and then Jupyter"
          echo "USER jovyan"
          echo "ENTRYPOINT [\"/bin/bash\", \"-lc\", \"start\"]"
        } > binder/Dockerfile
        echo "Updated binder/Dockerfile to use $IMAGE_REF and auto-run start"

    - name: Commit binder/Dockerfile
      uses: EndBug/add-and-commit@v9
      with:
        add: binder/Dockerfile
        message: "chore: update Binder base image"
        default_author: github_actions
