name: repo2docker-dockerhub
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Optionally convert README to index.ipynb
      run: |
        python -m pip install -U pip jupytext jupyterlab
        if [ -f README.md ]; then
          sed '/^<\!-- START RUN INFO/,/^<\!-- END RUN INFO/d;' README.md > index.md || cp README.md index.md
          jupytext -k python3 --to ipynb index.md || true
        fi

    - name: Commit index.ipynb
      uses: EndBug/add-and-commit@v9
      with:
        add: index.ipynb
        message: "CI: add/update index.ipynb"
        default_author: github_actions

    - name: Build and push with repo2docker (Docker Hub)
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        DOCKER_REGISTRY: docker.io
        IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
        # Do not set BINDER_CACHE (Quay-specific)
